- name: Demon on Play Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}

- name: Demon on Task Variables
  hosts: all
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.example.com