- name: Demo on Conditions
  hosts: all
  tasks:
    - name: execute if it is a centos machine
      debug:
        - msg: I am centos


    - name: execute if it is debian machine
      debug:
        - msg: I am debian