- name: Demo on Conditions
  hosts: all
  tasks:
    - name: execute if centos machine
      debug:
        msg: I am centos


    - name: execute if debiam machine
      debug:
        msg: I am debian