- name: Demo on handlers
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Update nginx Port Number
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx


    - name: Started Nginx
      systemd:
        name: nginx
        state: started

  handlers:
    - name: Restart Nginx
        systemd:
          name: nginx
          state: restarted
