- name: Demo on handlers
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present


    - Update Nginx Port Number


    - name: Start nginx
      systemd:
        name: nginx
          state: restarted