- name: Demo on handlers
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Update nginx Port Number
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf


    - name: Started Nginx
      systemd:
        name: nginx
        state: started

