- name: Demo on handlers
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Update nginx port number
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Retart nginx
      systemd:
        name: nginx
        state: restarted