- name: Install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Download {{ APP }} Component
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
    EXTRACT_DIR: /home/roboshop/catalogue
    APP_USER: roboshop

- name: Install NodeJS Modules
  community.general.npm:
    path: /home/roboshop/catalogue
#    executable: /bin/npm
#    unsafe_perm: yes
  APP_USER: roboshop
  #To resolve issue with catalogue not working i had to install npm in /home/roboshop/catalogue manually then restart catalogue service

- name: Update SystemD script for Catalogue Service
  ansible.builtin.replace:
    path: /home/roboshop/catalogue/systemd.service
    regexp: 'MONGO_DNSNAME'
    replace: "mongodb-aa.samdevops.tk"

- name: Setup SystemD script
  shell: mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service

- name: Start Catalogue Service
  systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes