- name: Install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Download {{ APP }} Schema
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
    EXTRACT_DIR: /home/roboshop/catalogue/catalogue-main
    APP_USER: root