- name: Download {{ APP }} Component
  get_url:
    url: "{{URL}}"
    dest: /tmp/{{COMPONENT}}.zip

- name: Remove old content
  file:
    path: "{{EXTRACT_DIR}}"
    state: absent

- name: Create directory for {{ COMPONENT }} Component
  file:
    path: "{{EXTRACT_DIR}}"
    state: directory
#  become_user: "{{ APP_USER }}"

- name: Unarchive {{ COMPONENT }} Component
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes
#  become_user: "{{ APP_USER }}"

- name: Move component Directory
  shell: mv {{EXTRACT_DIR}}/{{COMPONENT}}-main {{EXTRACT_DIR}}/{{COMPONENT}}

- name: Move Htdocs Directory
  shell: mv /usr/share/nginx/html/frontend-main/static/* /usr/share/nginx/html/.
  when: COMPONENT == "frontend"
#  #Decided to use shell command over ansible module, since we have static dir which is part of html dir causing the
#  recursive problem for ansible module
