- name: Download {{ APP }} Component
  get_url:
    url: "{{URL}}"
    dest: /tmp/{{APP}}.zip

- name: Remove old content
  file:
    path: "{{EXTRACT_DIR}}"
    state: absent

#- name: Create directory for {{ APP }} Component
#  file:
#    path: "{{EXTRACT_DIR}}"
#    state: directory
#  become_user: "{{ APP_USER }}"

- name: Unarchive {{ APP }} Component
  ansible.builtin.unarchive:
    src: /tmp/{{APP}}.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes
  become_user: "{{ APP_USER }}"

- name: Move Htdocs Directory
  shell: mv /usr/share/nginx/frontend-main/static/* /usr/share/nginx/html/.
  when: APP == "frontend"
#  #Decided to use shell command over ansible module, since we have static dir which is part of html dir causing the
#  recursive problem for ansible module
