- name: Set Hostname {{ COMPONENT }} Component
  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: Disbale auto shutdown for {{ COMPONENT }} component
  ansible.builtin.shell: disable-auto-shutdown

- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop
  when: APP == "catalogue" or APP == "user" or APP == "cart" or APP == "shipping" or APP == "payment"
  register: out

- name: Grab UID and GID of Roboshop User
  when: APP == "catalogue" or APP == "user" or APP == "cart" or APP == "shipping" or APP == "payment"
  set_fact:
    RS_UID: "{{out.uid}}"
    RS_GID: "{{out.group}}"