- name: Set Hostname {{ APP }} Component
  shell: set-hostname {{ APP }}

- name: Disbale auto shutdown for {{ APP }} component
  shell: disable-auto-shutdown

- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop
  when: APP == "catalogue" or APP == "user" or APP == "cart" or APP == "shipping" or APP == "payment"
  register: out