- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Download {{ COMPONENT }} Component
  ansible.builtin.include_tasks: curl_download.yml
  vars:
    EXTRACT_DIR: /home/roboshop/{{APP}}
    APP_USER: roboshop

- name: Install NodeJS Modules
  community.general.npm:
    path: /home/roboshop/catalogue
  #    executable: /bin/npm
  #    unsafe_perm: yes
  become_user: roboshop
  #To resolve issue with catalogue not working i had to install npm in /home/roboshop/catalogue manually then restart catalogue service

- name: Download {{ COMPONENT }} Component
  ansible.builtin.include_tasks: systemd.yml

