- name: Update SystemD script for {{ COMPONENT }} Service
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}-main/systemd.service
    regexp: "{{item.source}}"
    replace: "{{item.dest}}"
  loop:
    - {source: "MONGO_DNSNAME", dest: "mongodb-{{ENV}}.samdevops.tk"}
    - {source: "MONGO_ENDPOINT", dest: "mongodb-{{ENV}}.samdevops.tk"}
    - {source: "REDIS_ENDPOINT", dest: "redis-{{ENV}}.samdevops.tk"}
    - {source: "CATALOGUE_ENDPOINT", dest: "catalogue-{{ENV}}.samdevops.tk"}
    - {source: "CARTHOST", dest: "cart-{{ENV}}.samdevops.tk"}
    - {source: "USERHOST", dest: "user-{{ENV}}.samdevops.tk"}
    - {source: "AMQPHOST", dest: "rabbitmq-{{ENV}}.samdevops.tk"}
    - {source: "CARTENDPOINT", dest: "cart-{{ENV}}.samdevops.tk"}
    - {source: "DBHOST", dest: "mysql-{{ENV}}.samdevops.tk"}


- name: Setup SystemD script
  ansible.builtin.shell: mv /home/roboshop/{{COMPONENT}}/systemd.service /etc/systemd/system/{{COMPONENT}}.service

- name: Start {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes